title: awe.github.io
description: فروشگاه باورهای محدود کنده و اصلاح انها
name: awe.github.io
author: AWE
email: awebavar@gmail.com
theme: minima
baseurl: ""
url: "https://awe.github.io"
    shortname: site-disqus
